#!/usr/bin/env bash
# This script handles SIGTERM

function handle_sigterm() {
  echo "I am invincible!!!"
}

trap handle_sigterm SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
